config/routes.rb
TakeThis::Application.routes.draw do
  devise_for :users

  root :to => 'home#index', as: :home
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :likes, :title, :game, :author

  belongs_to :game
  belongs_to :author, class_name: "User", foreign_key: :user_id
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :released_on, :title, :articles

  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :check_user, only: [:new, :create]

  def index
  	@articles = {}
    Game.all.each do |game|
      @articles[game.title] = game.articles
    end
  end

  def show
  	@article = Article.find(params[:id])
  end

  def new
  end

  private

  def check_user
    unless current_user
      flash[:error] = "you must log in"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = {}
    Game.all.each do |game|
      @articles[game.title] = game.articles
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/new.html.haml
%h1 Articles#new
%p Find me in app/views/articles/new.html.haml

app/views/articles/show.html.haml
= @article.game.title

app/views/home/index.html.haml
- @articles.each do |game_title, articles|
  .game= game_title 
  .articles
    - articles.each do |article|
      .article_thumb
        = link_to article.title, article
        .author= "by #{article.author.name}"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "TakeThis"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #profile-panel
    #header
      =render "shared/header"
    #content
      .success= flash[:success]
      .error= flash[:error]
      = yield
    #footer

app/views/shared/_header.html.haml
#header-logo  
  .logo
    = link_to image_tag('template/logo.png'), home_path  
    %a#header-title
      %span Take
      %span This
  .punchline ...it's dangerous to go alone.

#main-controls
  .main-control.left
    .control-link
      = link_to image_tag(""), new_article_path 
    %span b
  .main-control.right
    .control-link
      = link_to image_tag(""), articles_path 
    %span a
#header-right
  #connect-links
    = link_to 'Sign in', new_user_session_path, :class => 'show-panel'
    = link_to 'Register', new_user_registration_path, :class => 'show-panel'